load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.6.1.2",
    url = "file:///home/firefly-dang/Downloads/protobuf-3.6.1.2.zip",
)
new_local_repository(
    name = "opencv",
    build_file = "opencv.BUILD",
    path = "/usr/include",
)
